name:                http2-grpc-types
version:             0.5.0.0
github:              "haskell-grpc-native/http2-grpc-haskell"
license:             BSD3
author:              "Lucas DiCioccio, Alejandro Serrano"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2018, 2019 Lucas DiCioccio, Alejandro Serrano"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Types for gRPC over HTTP2 common for client and servers.
category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/haskell-grpc-native/http2-grpc-haskell/blob/master/http2-grpc-types/README.md>

dependencies:
- base >= 4.10 && < 5
- binary >= 0.8.5 && < 0.11
- bytestring >= 0.10.8 && < 0.13
- case-insensitive >= 1.2.0 && < 1.3
- zlib >= 0.6.2 && < 0.8

library:
  source-dirs: src
  ghc-options: -Wall
